### ISSUE TITLE
test request e response con spid validator e accesso CNS CIE

### ISSUE THREAD

**Issue by Matt85R22** [italia/spid-keycloak-provider#1]
salve Luca ,
premetto che questa è una question e non una issue
ti contatto per farti sapere che stiamo realizzando un progetto che include l’autenticazione con SPID, 
utilizzando ed integrando KEYCLOAK come soluzione di identity ed access management già preesistente.

Riguardo allo stack tecnologico per la parte frontend abbiamo usato React v16,
per la parte backend utilizziamo java 1.8 ed il framework springboot.

Abbiamo completato, in ambiente di sviluppo il flusso di autenticazione con spid, però riscontriamo dei problemi relativamente allo spid validator.
Venerdì ho creato questo post sul forum agid che spiega più nei dettagli la problematica riscontrata :
https://forum.italia.it/t/dubbi-processo-validazione-request-e-response-usando-spid-validator/17350
 
Ti volevo chiedere se la request generata dal tuo applicativo era stata testata dallo spid validator, con particolare riferimenti ai messaggi d'errore.

Inoltre volevamo sapere se questo modulo potrebbe essere compatibile anche con CIE e CNS e parlare delle eventuali modifche da apportare.

Dalla documentazione che abbiamo letto la parte relativa alla CIE dovrebbe essere molto simile se non la stessa di quella che già sviluppata con lo spid-provider.

Per quanto riguarda invece la parte CNS ho già realizzato una soluzione che, senza usare plugin esterni,riesce a ricevere il certificato inviato dal client ed estrarne le informazioni che ci occorrono per
fare la lookup su un db interno di utenti su cui siamo gli owner. Lo stack tecnlologico è già quello esposto sopra, react e java springboot.

ti ringrazio in anticipo ,

Matteo

**Comment by lscorcia** [comment]
Ciao @Matt85R22 , la issue sul forum italia purtroppo non è più visibile. Ti posso confermare che ho testato l'accesso tramite spid-saml-check e non ho riscontrato errori, il sistema sembra funzionare (ho testato il branch keycloak-12, non ho più una installazione di Keycloak 11 su cui fare prove). I metadati generati non sono ancora compliant con l'avviso pubblico #29, ma è roba di poche differenze e comunque conviene sempre generare i metadati a mano.

Per la CNS, ho un altro progetto apposta: https://github.com/lscorcia/keycloak-cns-authenticator . Nel nostro scenario, gli utenti non sono noti a priori, per cui ho creato un authenticator che crea gli utenti a runtime sulla base dei dati contenuti nella CNS. Ti posso confermare che funziona, anche se non ho avuto il tempo di creare il wiki con tutta la documentazione. Per iniziare però puoi dare una occhiata al README.

Per CIE ID, non ho ancora provato l'integrazione - in linea teorica sembra anche più semplice di SPID perché più aderente al protocollo SAML. Più avanti dovrò sicuramente occuparmene, ma per il momento sono ancora in attesa che AGID mi approvi il metadato aggiornato sul mio sistema di Produzione... tocca aspettare.

**Comment by Matt85R22** [comment]
Ciao Luca , dopo un pò di tempo siamo riusciti a capire il problema relativo allo spid validator che ci impediva il test.

Era dovuto anche a delle configurazioni errate a livello di alias dns , che a volte traducevano nell' ip corrispondente a volte no , col risultato di avere delle configurazioni parziali all'interno delle cartelle di cache del validator all'interno del container.

Correggendo il problema e con l'occasione facendo l'upgrade a keycloak 11 e di conseguenza alla versione 1.04 dello spid-provider , non abbiamo più riscontrato questa problematica.

Riguardo ai test di spid validator , se vuoi ti aggiorno appena riesco a fare un punto della situazione, riscontriamo alcuni problemi .

Per la parte CNS e CIE , abbiamo dei dubbi , magari apriamo una question sul CNS authenticator.

Ti ringraziamo per il contributo che hai condiviso fino a ora! :)

**Comment by lscorcia** [comment]
Ciao @Matt85R22, sono contento che siate riusciti a proseguire l'attività. Io intanto posso confermarti che il nostro SP SPID basato su Keycloak 12 e questo plugin è stato accettato da AGID in produzione e dai nostri test abbiamo potuto verificare che funziona regolarmente.

In realtà, come riportato nel wiki, consiglio caldamente di utilizzare come base Keycloak 12.0.0-SNAPSHOT, perché hanno integrato upstream molte delle mie patch necessarie per SPID. Se vai a guardare il branch keycloak-12 potrai notare che il codice è molto più snello. Inoltre, siccome non ho più una installazione di Keycloak 11 a disposizione, non sto effettuando i backport delle mie nuove implementazioni su questa release (ad es. il branch keycloak-12 è in grado di generare in automatico il metadata SPID, e intendo aggiungere a breve qualche intervento per migliorare la compatibilità con l'Avviso SPID n. 29v3).

I lati negativi di usare la versione 12.0.0-Snapshot sono due:
1) Dovete compilare tutto a mano, non posso distribuire i binari del pacchetto perché le dipendenze dai pacchetti di Keycloak 12 non sono disponibili pubblicamente;
2) Gli aggiornamenti del DB di Keycloak possono causare qualche problema, per cui sconsiglio fortemente di usare questa release in produzione, ma se siete in fase di sviluppo o test dell'implementazione e potete aspettare la release ufficiale prima di andare in produzione, allora si può fare.

Nel mio ambiente di test, spid-saml-check riferisce tutti i controlli come superati correttamente (a parte quelli sul certificato, ma questi non dipendono dal plugin). Spid-testenv2 invece è un po' che non lo provo, ma l'ultima volta che ci ho guardato funzionava anche lui. Purtroppo quest'ultimo applicativo non è molto allineato alle ultime specifiche e agli IdP reali, quindi non ci ho perso troppo tempo.

Aprimi pure delle issue per i problemi riscontrati con SPID Validator, per la CNS proverò a ritagliarmi un po di tempo per scrivere la documentazione, ma ne parliamo di là se vi serve una mano.

Lieto di aver fatto qualcosa di utile, a presto!

**Comment by nicolabeghin** [comment]
Chiudo in quanto vecchio di 3 anni
