### ISSUE TITLE
Metadata per Ente Aggregatore

### ISSUE THREAD

**Issue by francucchi** [italia/spid-keycloak-provider#19]
Buongiorno,

da diversi mesi ormai, la mia azienda ha assunto per AgID il ruolo di Ente Aggregatore.
Attualmente stiamo utilizzando un'infrastruttura di autenticazione proprietaria che gestisce all'incirca due/tre mila enti e stavamo valutando la possibilità di integrare le configurazioni keycloak all'interno del metadata da Aggregatore che stiamo utilizzando.
Per fare questo avremmo però la necessità di poter generare asserzioni, avvalendoci del certificato di federazione fornitoci da AgID con relativa private key.
Chiedo cortesemente se questa modalità fosse possibile ed in caso affermativo, quale procedura seguire a tale scopo.

Grazie

**Comment by lscorcia** [comment]
Ciao @francucchi , purtroppo non sono familiare con le procedure previste per i soggetti aggregatori. Se riesci a spiegarmi meglio cos'è che esattamente vi serve e in quale fase del processo siamo (accreditamento/generazione del metadato/erogazione del servizio) possiamo provare a ragionarci su insieme.

**Comment by lscorcia** [comment]
Il supporto ai metadati degli SP privati è stato migliorato tramite la PR #30 inclusa nella release 1.0.12. Se ciò è sufficiente per chiudere la issue vi prego di farmi sapere. A presto e grazie

**Comment by francucchi** [comment]
Chiedo scusa ma purtroppo non riusciamo al momento a verificare la nuova release causa varie attività in sovrapposizione.
Vorrei solo chiedere se è ora possibile caricare sia la chiave sia i metadati che abbiamo già in nostro possesso e in utilizzo tramite un software fatto in casa o se di fatto questi non possano essere riutilizzati su questa nuova release.
Per il resto suppongo si possa chiudere la issue e in caso eventualmente aprirne un'altra quando potremo completare le verifiche.
Grazie tanto per il lavoro fatto.

**Comment by MrIvv** [comment]
Ciao @lscorcia,

sto sperimentando il vostro plugin per un Ente aggregatore e ho riscontrato questi 2 aspetti che vorrei valutare con voi:

1) I soggetti aggregatori che rilasciano i propri metadata verso Agid per la registrazione potrebbero trovare poco elegante generare 9 endpoints di ritorno per un realm e soprattutto quando si hanno 5 AttributeConsumingService differenti che si vogliono usare con ogni IDP configurato ci si ritroverebbe da dover registrare 9 endpoints ciascuno con 5 AttributeConsumingService differenti.

L'idea sarebbe quella di configurare si 9 IDP + 1 Generico che viene registrato presso Agid come un endpoint di ritorno per la Saml response per ciascun realm anziche averne 9. 
Guardando questa soluzione e' fattibile con il vostro plugin pero' riscontro 2 problematiche verso la validazione della response in 2 punti (Validazione con la risposta "SpidSamlCheck_nr29" che e' giusto e il Validatore che conferma "Errors.INVALID_SAML_RESPONSE").
Qui nasce la mia domanda, e' giusto adeguare il validatore della Saml response per questa soluzione? Voi cosa ne pensate di questo?

2) Dopo la prima domanda mi viene spontaneo da chiedere come si potrebbe fare che un IDP possa richiedere differenti AttributeConsumingService e anche generare lo SpidMetadata con i differenti AttributeConsumingService? Pensate di sviluppare qualcosa al riguardo? Di seguito l'esempio del problema.
Esempio: 
2 applicativi usano lo stesso Realm, ma entrambi necessitano di 2 AttributeConsumingService differenti (il primo applicativo un'ampia tabella di dati e il secondo molto ridotta tabella di dati) e secondo Agid si dovrebbe richiedere il minimo di dati necessari per ogni applicativo. Ora come ora vedendo il vostro plugin non e' possibile ne Generare piu AttributeConsumingService per un unico IDP e tanto meno cambiare in maniera dinamica il range di dati da richiedere.

Resto in attesa di un vostro confronto
Grazie mille
