### ISSUE TITLE
Errore "verifyRedirectSignature" durante Logout con spid-saml-check

### ISSUE THREAD

**Issue by erapsag** [italia/spid-keycloak-provider#20]
Salve, riscontro questo errore quando provo il logout dalla mia applicazione, dopo avere effettuato il login tramite lo spid-saml-check con il test di "Response Corretta":
```
keycloak-spid    | 15:14:45,069 ERROR [org.keycloak.broker.spid.SpidSAMLEndpoint] (default task-16) validation failed: org.keycloak.common.VerificationException: org.keycloak.common.VerificationException: Invalid query param signature
keycloak-spid    |      at org.keycloak.keycloak-services@12.0.0//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:169)
keycloak-spid    |      at org.keycloak.keycloak-services@12.0.0//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:127)
...
keycloak-spid    | Caused by: org.keycloak.common.VerificationException: Invalid query param signature
keycloak-spid    |      at org.keycloak.keycloak-services@12.0.0//org.keycloak.protocol.saml.SamlProtocolUtils.verifyRedirectSignature(SamlProtocolUtils.java:166)
keycloak-spid    |      ... 81 more
```
In passato, testando lo stesso giro su Windows non avevo mai avuto questo problema, mi si presenta adesso che ho installato il tutto su un Ubuntu Server.
Impostando su "ON" il parametro "Backchannel Logout" nelle configurazioni dell'IdP il problema scompare, ed il logout sembra avvenire in maniera corretta. Devo dire però che su windows, senza il "Backchannel Logout" attivato, dopo il logout arrivavo ad una pagina sempre di spid-saml-check dove mi notificava del logout effettuato con successo, adesso invece atterro sempre sulla mia applicazione.
E' successo a qualcuno? avevo già sentito di questo "Backchannel Logout" in qualche altra Issue, è un parametro che può/deve essere attivo per tutti gli IdP?

**Comment by lscorcia** [comment]
Ciao @erapsag , scusa il ritardo nella risposta, ho dovuto mettere da parte il progetto per qualche settimana. 
Ho provato oggi lo stesso giro su Ubuntu con Keycloak 13, l'ultimo spid-saml-check e l'ultima versione 1.0.8 del provider e non ho riscontrato problemi né con Backchannel Logout attivo né con Backchannel Logout disattivato. E' possibile che il difetto sia stato risolto indipendentemente da questo progetto.

L'idea generale è che con il Backchannel Logout è il server a inviare una richiesta di logout all'IdP, quindi è generalmente più affidabile ma non può fornire feedback all'utente in caso di problemi (timeout, errori dell'IdP, etc.). Se il logout avviene dal front channel è invece il browser dell'utente a dover fare un giro di redirect al gestore SPID, con più possibilità di fallimento ma in questo caso l'utente dovrebbe averne evidenza (timeout, errori dell'IdP, etc).
Personalmente consiglio quindi di attivare la funzione di Backchannel Logout.

Se hai possibilità, ti chiederei di riprovare con tutte le versioni aggiornate dei diversi componenti e farmi sapere se riesci a riprodurlo.
