### ISSUE TITLE
Identity Provider Configurazioni

### ISSUE THREAD

**Issue by MrIvv** [italia/spid-keycloak-provider#26]
Salve,

stavo analizzando il vostro lavoro con questo plugin per realizzare un Idp personalizzato e mi sono scontrato con questo problema:
nel caso si cambi PROVIDER_ID con un nome personalizzato all'interno della Idp Factory non mi apre più la pagina di configurazione del idp sia nel vostro plugin sia in quello da me realizzato.
C'è un modo per settare l'id senza andar a sovrascrivere un IDP già presente?
![erroreKeycloak](https://user-images.githubusercontent.com/77835318/119473428-70f17000-bd4b-11eb-8c34-241a9a00db13.PNG)

**Comment by lscorcia** [comment]
Dovrebbe funzionare. Ti consiglio di controllare 1) che il file di UI sotto /main/src/main/resources/theme-resources/resources/partials abbia l'id corretto nel filename 2) di aver disattivato la cache dei temi di keycloak come da file README.

**Comment by MrIvv** [comment]
Grazie mille!
L'errore mio era nel nome del file del partials. Erano 2 nomi differenti fra Provider_ID e nome della pagina di configurazioni html ( realm-identity-provider-Nomeprovider.html ).
