### ISSUE TITLE
Cambiare chiave RSA per firma del metadata

### ISSUE THREAD

**Issue by angelolamonaca** [italia/spid-keycloak-provider#28]
Come é possibile cambiare la chiave RSA per la firma del metadata?

**Comment by bozzadavide** [comment]
Chiave privata e certificato li puoi caricare nel tuo realm nella sezione keys. Come scritto nella documentazione keycloak può gestire solo una chiave per realm quindi tutte le tue richieste SAM per IDP diversi verranno firmate con la stessa chiave.
