### ISSUE TITLE
Keycloak releases

### ISSUE THREAD

**Issue by freddy34** [italia/spid-keycloak-provider#39]
Possibile sapere se sono previsti dei rilasci per le versioni di Keycloak superiori alla 16.1.1? dalla 17.x inoltre Keycloak ha deprecato la distribuzione basata su WildFly (taggandola nel mondo container come "legacy") a favore di quella su Quarkus. Anche in questo caso vi sono delle previsioni? Grazie

**Comment by nicolabeghin** [comment]
Chiuso, rilasciata compatibilità Keycloak 23
