### ISSUE TITLE
https://demo.spid.gov.it/ raises error: Formato richiesta non corretto. TypeError: Cannot read property 'SpidSpAuthnReqCheck' of undefined

### ISSUE THREAD

**Issue by skribble-freddy** [italia/spid-keycloak-provider#43]
Setup done as described in Wiki https://github.com/italia/spid-keycloak-provider/wiki with:
* Keycloak 19.0.3
* spid-provider.jar [1.0.13](https://github.com/italia/spid-keycloak-provider/releases/tag/1.0.13)

Issuing a "Link account" in the profile redirects towards demo.spid.gov.it and raises this error:

<img width="385" alt="SPID-Error" src="https://user-images.githubusercontent.com/115150382/198984114-9570fbae-91fd-4a1e-b895-4820b8060776.png">

Attached the SAML-AuthnRequest Request
[SPID-Error_details.json.txt](https://github.com/italia/spid-keycloak-provider/files/9900144/SPID-Error_details.json.txt)

as well as the SP-Metadata-Validation
<img width="786" alt="SPID-MetaData_valdiation01" src="https://user-images.githubusercontent.com/115150382/198984214-1d8d90ee-b549-4803-a07e-9e4b0963434b.png">
<img width="972" alt="SPID-MetaData_valdiation02" src="https://user-images.githubusercontent.com/115150382/198984218-51adb8ca-f9e1-4bc1-8b0d-51b3dbb178d7.png">

**Comment by nicolabeghin** [comment]
Chiudo in quanto vecchio di 2 anni
