### ISSUE TITLE
First Broker Login ... not found

### ISSUE THREAD

**Issue by gadaxmagicgadax** [italia/spid-keycloak-provider#46]
salve,

sto seguendo le istruzioni per la configurazione dal wiki : https://github.com/italia/spid-keycloak-provider/wiki/Configuring-the-Authentication-Flow

A un certo punto si chiede di accedere in Authentication e "copiare" il "First Broker Login". Purtroppo il First Broker Login non compare nella lista.

Ho idea che la sua definizione sia nel provider che ho preparato seguendo le istruzioni di build in : https://github.com/italia/spid-keycloak-provider. Il provider si vede nella console di KeyCloak e in effetti ho configurato due IdP e relativi SP. Il First Broker Login non compare nella lista.

Qualche idea ?
grazie
saluti
Giovanni

**Comment by nicolabeghin** [comment]
@gadaxmagicgadax il "First Broker Login" fa parte dei flow standard, verifica la tua installazione Keycloak perchè deve esistere.
