### ISSUE TITLE
Indicazioni sulla Wiki non esatte (Service Provider Entity ID e AuthnContextClassRef)

### ISSUE THREAD

**Issue by frabnet** [italia/spid-keycloak-provider#47]
Salve, volevo contribuire al miglioramento della Wiki, ma prima di farlo volevo chiedere se effettivamente esiste un errore oppure il mio è un caso particolare.

Alla pagina https://github.com/italia/spid-keycloak-provider/wiki/Defining-SPID-IdPs

E' riportato:

> **Service Provider Entity ID:** set to the Entity ID you want to use to identify your Service Provider;
> TIP: While the Service Provider Entity ID has to be an URI, there is no need for it to be a real, working internet address. It is just an identifier for your organization Service Provider. Make sure to choose it wisely, as it can't be changed once it has been shared with the federation;
> 

> **AuthnContext ClassRefs**: enter - in order from the most preferred to the least preferred - one or more of the SPID Authentication Level classes. Valid values are:
> 
> https://www.spid.gov.it/SpidL3
> https://www.spid.gov.it/SpidL2
> https://www.spid.gov.it/SpidL1

In realtà, dopo aver sbattuto la testa per svariate ore sullo SPID Validator reso a disposizione (https://demo.spid.gov.it/), che restituiva un errore assurdo (Gateway Timeout), ho scoperto, soltanto eseguendo il Validator in locale (https://github.com/italia/spid-saml-check), che:

1) L'attributo entityID deve essere impostato esattamente come il realm di keycloak e non "a caso" come indicato
2) Solo un AuthnContextClassRef è permesso

```
{
  test_id: '',
  result: 'failure',
  test: "The Issuer's value MUST be equal to entityID",
  value: 'https://sso.aspbassaromagna.it/realms/bandi',
  references: [],
  method: ''
}
{
  test_id: '',
  result: 'failure',
  test: 'Only one AuthnContexClassRef element MUST be present',
  value: "['<AuthnContextClassRef>https://www.spid.gov.it/SpidL3</AuthnContextClassRef>', '<AuthnContextClassRef>https://www.spid.gov.it/SpidL2</AuthnContextClassRef>', '<AuthnContextClassRef>https://www.spid.gov.it/SpidL1</AuthnContextClassRef>']",
  references: [],
  method: ''
}
```

**Comment by nicolabeghin** [comment]
@frabnet una PR è ben accetta, grazie!

**Comment by nicolabeghin** [comment]
[Wiki aggiornata](https://github.com/italia/spid-keycloak-provider/wiki/Defining-SPID-IdPs), chiudo
