### ISSUE TITLE
keycloak.v2 theme

### ISSUE THREAD

**Issue by pibragh** [italia/spid-keycloak-provider#52]
The last keycloak release (21.x) has removed the _keyclock_ theme, so is no longer possible to configure the SPID IdP.
Is there any plan to migrate to _keycloak.v2_ theme ?

**Comment by lucrus73** [comment]
Since you have not received any answers, and since I also need this provider to work with newer releases of KC, I could try to contribute the changes to this project in order to make it compatible with keycloak.v2 theme.

I know Java, but I'm new to this project, so maybe @lscorcia could just give me a few hints about where to start from?

**Comment by pibragh** [comment]
It would be great

**Comment by marcoserafini2** [comment]
Ciao @lucrus73 c'è tutta [una discussione](https://github.com/keycloak/keycloak/discussions/11849) su Keycloak.
Anche @lscorcia aveva aperto [una issue](https://github.com/keycloak/keycloak/issues/17958) in merito.

Aggiungo, come [puoi leggere qui](https://github.com/keycloak/keycloak/issues/15344),  che il supporto alla vecchia console/tema è stato rimosso prima del supporto ai provider con configurazioni personalizzate, il che comporta anche l'aggiornamento di Keycloack #57

**Comment by nicolabeghin** [comment]
PR sottomessa per compatibilità Keycloak 23 (no interfaccia grafica) https://github.com/italia/spid-keycloak-provider/pull/59

**Comment by nicolabeghin** [comment]
Per chi avesse voglia/tempo di aiutare: qui https://github.com/italia/spid-keycloak-provider/pull/59 l'inizio dell'adattamento della UI del provider basato su `ConfiguredProvider` come richiesto da Keycloak 23.x

**Comment by nicolabeghin** [comment]
Per chi avesse voglia/tempo di aiutare: qui https://github.com/italia/spid-keycloak-provider/pull/59 l'inizio dell'adattamento della UI del provider basato su `ConfiguredProvider` come richiesto da Keycloak 23.x

**Comment by nicolabeghin** [comment]
Ongoing discussion su repository Keycloak: https://github.com/keycloak/keycloak/discussions/25862

**Comment by enicolaescu** [comment]
Keycloak 24.0.1 has been recently released, I tested the provider by renaming the id to "spid-saml" and I can confirm that on the IDP configuration page both SAML and custom configs are shown

The only problem I see, besides having to rename the id to include "saml", is that the SAML configs are not shown when creating a new spid idp, they are only visibile when editing an existing idp. It doesn't cause any issues though

**Comment by nicolabeghin** [comment]
> Keycloak 24.0.1 has been recently released, I tested the provider by renaming the id to "spid-saml" and I can confirm that on the IDP configuration page both SAML and custom configs are shown
> 
> The only problem I see, besides having to rename the id to include "saml", is that the SAML configs are not shown when creating a new spid idp, they are only visibile when editing an existing idp. It doesn't cause any issues though

I confirm the same, version [24.0.1](https://github.com/italia/spid-keycloak-provider/releases/tag/24.0.1) of the provider has just been released along with indications on how to change the provider ID from the DB so that it's not required to change all existing IdP configurations
