### ISSUE TITLE
E' una soluzione completa e funzionante?

### ISSUE THREAD

**Issue by progaslcas** [italia/spid-keycloak-provider#54]
Ciao a tutti.
Ho un applicazione strutturata in due parti:
-front end con reactjs
-back end con spring boot

Da giorni ormai che cerco una buona soluzione per integrare l'autenticazione con lo spid nella mia applicazione,ma purtroppo noto che java spid sdk è work in progress,mentre l'altra libreria chiamata spid-spring non ha nemmeno una versione di release.

In sintesi sono molto confuso su quale mi converrebbe utilizzare e questa libreria "**spid-keycloak-provider**" mi sembra abbastanza interessante. Però leggo che nessuno la utilizza in produzione. Come mai?

Cosa mi consigliate di fare per integrare lo spid nella mia applicazione ? Devo reinventare la ruota da 0?

Grazie mille in anticipo

**Comment by progaslcas** [comment]
Grazie per le informazioni 👍

**Comment by damikael** [comment]
Ciao a tutti,
mi permetto di inserirmi nella discussione, sperando di fare cosa gradita, per informare che il progetto [spid-php](https://github.com/italia/spid-php) permette di realizzare un Proxy SPID/CIE in poco tempo, è conforme completamente alle regole tecniche e agli ultimi avvisi SPID, superando tutti i controlli di spid-saml-check, ed è installabile anche tramite Docker.
Ad oggi si contano più di 80 installazioni funzionanti in produzione con spid-php.

Saluti,
Michele
