### ISSUE TITLE
Richiesta modifica documentazione su mapping spid attributes

### ISSUE THREAD

**Issue by Samuele-Z** [italia/spid-keycloak-provider#55]
Proporrei di aggiornare il wiki.
Nella pagina
https://github.com/italia/spid-keycloak-provider/wiki/Mapping-SPID-attributes
Tra i dati indicati nella sezione Basic attributes ci sono solo nome e cognome.
Stiamo configurando Keycloak 19.0.3 ed abbiamo notato che va aggiunto anche il campo fiscalNumber.
Questi campi vengono inseriti nel metadata alla sezione AttributeConsumingService. L'identity provider poi fornirà nella risposta i dati per i soli campi indicati in questa sezione. Se non si inserisce il campo fiscalNumber nella risposta mancherà il codice fiscale.
Nei log comparirà l'errore: 
ERROR [org.keycloak.broker.spid.SpidSAMLEndpoint] (executor-thread-1) no principal in assertion; expected: ATTRIBUTE(fiscalNumber)

**Comment by nicolabeghin** [comment]
Se utile qui un programmino per impostare programmaticamente tutti gli identity provider SPID con relativi mapper - utilizzato con successo in produzione https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client
