### ISSUE TITLE
Supporto alla versione 22 o superiore

### ISSUE THREAD

**Issue by pingrami** [italia/spid-keycloak-provider#57]
E' previsto il supporto alla versione 22 (o superiore) di Keycloak e relativo adeguamento alla nuova interfaccia 'keyclaok.v2'?

**Comment by lucrus73** [comment]
duplicato di https://github.com/italia/spid-keycloak-provider/issues/52

**Comment by nicolabeghin** [comment]
PR sottomessa per compatibilità Keycloak 23 (no interfaccia grafica) https://github.com/italia/spid-keycloak-provider/pull/59

**Comment by nicolabeghin** [comment]
Per chi avesse voglia/tempo di aiutare: qui https://github.com/italia/spid-keycloak-provider/pull/59 l'inizio dell'adattamento della UI del provider basato su `ConfiguredProvider` come richiesto da Keycloak 23.x

**Comment by nicolabeghin** [comment]
Per chi avesse voglia/tempo di aiutare: qui https://github.com/italia/spid-keycloak-provider/pull/59 l'inizio dell'adattamento della UI del provider basato su `ConfiguredProvider` come richiesto da Keycloak 23.x

**Comment by Ettore-Morasso** [comment]
Ciao,
innanzitutto complimenti ai contributori per l'ottimo lavoro svolto su questa estensione, tuttavia come altri leggendo mi trovo nella stessa situazione di incompatibilità dell'estensione con le più recenti versioni di keycloak. Vorrei chiedere a tal proposito se esiste una roadmap per il rilascio della nuova estensione o, più semplicemente una stima sui tempi necessari.
Grazie.

**Comment by nicolabeghin** [comment]
@Ettore-Morasso il plugin dovrebbe funzionare senza problemi, il problema è la sua configurazione se fatta da UI, dato che da standard dalle ultime versioni non è possibile estendere l'interfaccia di configurazione di un IdP custom. Qui la discussione sul repo ufficiale Keycloak https://github.com/keycloak/keycloak/discussions/25862

**Comment by Ettore-Morasso** [comment]
Grazie @nicolabeghin ,
confermo che il plugin funziona correttamente sulla versione 23.0.5, al netto dei problemi con la ui.
Il progetto del configuratore rest anch'esso funzione egregiamente anche se alcune chiamate e alcuni valori default nel file di configurazione devono essere adeguati ai nuovi endpoint di keycloak.
Grazie per il lavoro svolto.

**Comment by pingrami** [comment]
Ciao @Ettore-Morasso, sapresti indicarmi che versione del plugin hai utilizzato?

**Comment by Ettore-Morasso** [comment]
Ciao @pingrami ,
devi usare il repo git di Nicola, branch "upgrade_keycloak_23", lo trovi qui: https://github.com/nicolabeghin/keycloak-spid-provider/tree/upgrade_keycloak_23
fai la build come al solito e poi se guardi la risposta che mi ha dato Nicola vedi che c'è un link al tool di configurazione per i vari idp spid....c'è qualcosina da sistemare lì ma funziona più che bene.
Saluti.

**Comment by nicolabeghin** [comment]
> link al tool di configurazione per i vari idp spid....c'è qualcosina da sistemare lì ma funziona più che bene.

@Ettore-Morasso sarebbe utile se potessi indicare cosa vada aggiornato nel client o direttamente sottomettere una PR - grazie! 

@pingrami a breve farò il merge del branch in oggetto così da creare il JAR pronto all'uso

**Comment by nicolabeghin** [comment]
1.0.16 rilasciata https://github.com/nicolabeghin/keycloak-spid-provider/releases/tag/1.0.16 con JAR pronto all'uso

Ho da pochissimo avuto anche i permessi di maintainer sul repo `italia/spid-keycloak-provider` e provvederò ad allineare

**Comment by Ettore-Morasso** [comment]
Ciao Nicola,
a breve farò una pr e valuterai.
Grazie

**Comment by Ettore-Morasso** [comment]
Ciao Nicola, il codice sarebbe pronto ma chiaramente non posso fare commit e creare la pr su questo repo non avendovi alcun diritto, quindi come vogliamo fare? crei un branch su cui mi dai accesso, o  semplicemente ti invio i file?

**Comment by nicolabeghin** [comment]
@Ettore-Morasso su GitHub funziona che 
1. fai il fork del repository -> ti crea qualcosa tipo `ettore-morasso/keycloak-spid-provider-configuration-client`
2. committi quanto devi in `ettore-morasso/keycloak-spid-provider-configuration-client`
3. sottometti PR dal tuo repo a quello originario

**Comment by Ettore-Morasso** [comment]
Ciao Nicola,
la pull request è stata fatta ( https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client/pull/5 ).
Saluti

**Comment by nicolabeghin** [comment]
> Ciao Nicola, la pull request è stata fatta ( [nicolabeghin/keycloak-spid-provider-configuration-client#5](https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client/pull/5) ). Saluti

aggiunti alcuni commenti prima di fare il merge, grazie!

**Comment by nicolabeghin** [comment]
Chiudo issue in quanto conclusa con PR https://github.com/italia/spid-keycloak-provider/pull/59
