### ISSUE TITLE
Errore check strict metadata autogenerato

### ISSUE THREAD

**Issue by rossanoros** [italia/spid-keycloak-provider#58]
Salve,

riscontro le seguenti problematiche nel check strict (produzione) della piattaforma [https://demo.spid.gov.it/](https://demo.spid.gov.it/):

![image](https://github.com/italia/spid-keycloak-provider/assets/12772828/e77c0e14-6e50-4bed-abc2-f41e9c6db1cc)

Avete idea di quale possa essere il problema?

Grazie!

**Comment by nicolabeghin** [comment]
Sono errori sul certificato SSL, non derivanti dal plugin - verificate le linee guida AGID!
