### ISSUE TITLE
Aggiunta di più identity provider

### ISSUE THREAD

**Issue by dvdcsc** [italia/spid-keycloak-provider#63]
Nella wiki viene detto di aggiungere un identity provider per ogni servizio con cui ci si vuole interfacciare (Aruba, Poste, Infocert etc...).
Questo non è possibile in quanto alias e provider id sono fissi su "spid-saml" e non modificabili alla creazione di un nuovo identity provider. è possibile ovviare a questo problema in qualche modo? (Sto utilizzando la versione 24.0.1 di Keycloak)

Inoltre sto provando ad interfacciarmi con il server di test [spid-saml-check](https://github.com/italia/spid-saml-check) per testare l'autenticazione tramite spid fittizio ma non mi è chiarissimo come vanno impostati gli URL dei metadata rispettivamente su Keycloak e spid-saml-check

**Comment by nicolabeghin** [comment]
Ciao effettivamente da UI non permette di inserire alias differenti per il medesimo provider sebbene in realtà sia qualcosa di assolutamente fattibile (credo sia una regression sull'interfaccia web). Ti consiglio di utilizzare il client di configurazione automatica, che funziona tramite REST aggirando i problemi della UI e che evita di dover fare tutti i passaggi a mano, oltre che limitando l'errore umano ref. https://github.com/nicolabeghin/keycloak-spid-provider-configuration-client
